// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// 載入順序：先讀 .env.local（本機開發金鑰），再讀 .env（fallback）。
// .env.local 的值會覆蓋 .env，確保開發環境連到正確的 Supabase。
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
dotenv.config(); // fallback：補上 .env.local 沒有的變數
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
